name: persistence
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - notebook
  - ipympl
  - ipywidgets
  - pip
  - pip:
      # Add pip-only packages below
      # - your-package-name
